"""
Executor - Executes plans step by step using tools
"""
from typing import List, Optional, Dict, Any, Callable
from dataclasses import dataclass, field
from datetime import datetime
import time

from .state import PlanState, PlanStep, PlanStatus


@dataclass
class ExecutionResult:
    """Result of executing a step or entire plan."""
    success: bool
    step_id: Optional[int] = None
    action: str = ""
    target: str = ""
    output: str = ""
    error: Optional[str] = None
    duration: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "step_id": self.step_id,
            "action": self.action,
            "target": self.target,
            "output": self.output,
            "error": self.error,
            "duration": round(self.duration, 3),
            "timestamp": self.timestamp,
        }


class Executor:
    """
    Executes plans generated by the Planner.

    The executor:
    1. Takes a PlanState with steps
    2. Executes steps one by one
    3. Handles errors and recovery
    4. Reports results back to the planner

    The executor uses tools from the tools module to perform actions.
    """

    name = "executor"
    description = "Executes plans using available tools"

    def __init__(
        self,
        root: str,
        tools: Optional[Dict[str, Callable]] = None,
    ):
        """
        Initialize the executor.

        Args:
            root: Repository root path
            tools: Dict of tool_name -> tool_function
                  e.g., {"read_file": read_file_func, "write_file": write_file_func}
        """
        self.root = root
        self.tools = tools or {}
        self.state: Optional[PlanState] = None
        self.execution_history: List[ExecutionResult] = []

    def set_tools(self, tools: Dict[str, Callable]) -> None:
        """Set or update the available tools."""
        self.tools.update(tools)

    def load_plan(self, state: PlanState) -> None:
        """Load a plan from PlanState."""
        self.state = state
        self.state.status = PlanStatus.EXECUTING
        self.execution_history.clear()

    def execute_step(self, step: PlanStep) -> ExecutionResult:
        """
        Execute a single step.

        Args:
            step: The PlanStep to execute

        Returns:
            ExecutionResult with the outcome
        """
        start_time = time.time()

        # Check if step has dependencies
        if step.dependencies:
            for dep_id in step.dependencies:
                dep_step = self._get_step(dep_id)
                if dep_step and dep_step.status != "completed":
                    return ExecutionResult(
                        success=False,
                        step_id=step.step_id,
                        action=step.action,
                        target=step.target,
                        error=f"Dependency step {dep_id} not completed",
                        duration=time.time() - start_time,
                    )

        # Get the tool for this action
        tool = self.tools.get(step.action)
        if not tool:
            return ExecutionResult(
                success=False,
                step_id=step.step_id,
                action=step.action,
                target=step.target,
                error=f"Unknown action: {step.action}. Available: {list(self.tools.keys())}",
                duration=time.time() - start_time,
            )

        # Execute the tool
        try:
            # Handle different action types
            if step.action == "read_file":
                result = tool(step.target)
            elif step.action == "write_file":
                # For write, we need content - should come from step description or plan
                # For now, assume the tool handles getting content
                result = tool(step.target)
            elif step.action == "search_code":
                result = tool(step.target)
            elif step.action == "grep":
                result = tool(step.target)
            elif step.action == "run_command":
                result = tool(step.target)
            else:
                result = tool(step.target)

            # Update step status
            if self.state:
                self.state.update_step(
                    step.step_id,
                    status="completed",
                    result=str(result)[:500],  # Truncate result
                )

            exec_result = ExecutionResult(
                success=True,
                step_id=step.step_id,
                action=step.action,
                target=step.target,
                output=str(result)[:1000],  # Truncate
                duration=time.time() - start_time,
            )

            self.execution_history.append(exec_result)
            return exec_result

        except Exception as e:
            error_msg = str(e)
            if self.state:
                self.state.update_step(
                    step.step_id,
                    status="failed",
                    error=error_msg,
                )

            exec_result = ExecutionResult(
                success=False,
                step_id=step.step_id,
                action=step.action,
                target=step.target,
                error=error_msg,
                duration=time.time() - start_time,
            )

            self.execution_history.append(exec_result)
            return exec_result

    def execute_all(self, stop_on_error: bool = True) -> List[ExecutionResult]:
        """
        Execute all steps in the plan.

        Args:
            stop_on_error: If True, stop on first error

        Returns:
            List of ExecutionResults
        """
        if not self.state:
            return []

        results = []
        self.state.status = PlanStatus.EXECUTING

        while True:
            step = self.state.get_next_pending_step()
            if not step:
                break

            result = self.execute_step(step)
            results.append(result)

            if not result.success and stop_on_error:
                self.state.status = PlanStatus.FAILED
                self.state.error_message = result.error
                break

        # Check if all steps completed
        if self.state and all(s.status == "completed" for s in self.state.plan):
            self.state.status = PlanStatus.COMPLETED

        return results

    def execute_until(self, step_id: int, stop_on_error: bool = True) -> List[ExecutionResult]:
        """
        Execute steps until reaching step_id.

        Args:
            step_id: Target step ID
            stop_on_error: Stop on first error

        Returns:
            List of ExecutionResults
        """
        if not self.state:
            return []

        results = []
        while True:
            step = self.state.get_next_pending_step()
            if not step or step.step_id > step_id:
                break

            result = self.execute_step(step)
            results.append(result)

            if not result.success and stop_on_error:
                break

        return results

    def retry_step(self, step_id: int) -> ExecutionResult:
        """
        Retry a failed step.

        Args:
            step_id: Step ID to retry

        Returns:
            ExecutionResult
        """
        step = self._get_step(step_id)
        if not step:
            return ExecutionResult(
                success=False,
                step_id=step_id,
                error="Step not found",
            )

        # Reset step status
        self.state.update_step(step_id, status="pending", error=None)

        return self.execute_step(step)

    def skip_step(self, step_id: int, reason: str = "") -> ExecutionResult:
        """
        Skip a step.

        Args:
            step_id: Step ID to skip
            reason: Why it was skipped

        Returns:
            ExecutionResult
        """
        if self.state:
            self.state.update_step(step_id, status="skipped", error=reason)

        return ExecutionResult(
            success=True,
            step_id=step_id,
            action="skip",
            output=f"Skipped: {reason}",
        )

    def _get_step(self, step_id: int) -> Optional[PlanStep]:
        """Get a step by ID."""
        if not self.state:
            return None
        for step in self.state.plan:
            if step.step_id == step_id:
                return step
        return None

    def get_next_step(self) -> Optional[PlanStep]:
        """Get the next pending step."""
        if self.state:
            return self.state.get_next_pending_step()
        return None

    def get_execution_summary(self) -> Dict[str, Any]:
        """Get a summary of the execution."""
        if not self.state:
            return {"error": "No plan loaded"}

        total = len(self.state.plan)
        completed = sum(1 for s in self.state.plan if s.status == "completed")
        failed = sum(1 for s in self.state.plan if s.status == "failed")
        pending = sum(1 for s in self.state.plan if s.status == "pending")

        return {
            "total_steps": total,
            "completed": completed,
            "failed": failed,
            "pending": pending,
            "status": self.state.status.value,
            "history": [r.to_dict() for r in self.execution_history],
        }


class ToolExecutor:
    """
    Executor that uses tool instances directly.

    This is a more advanced executor that works with Tool objects
    instead of just functions.
    """

    def __init__(self, root: str):
        self.root = root
        self.tool_instances: Dict[str, Any] = {}

    def register_tool(self, tool_instance: Any) -> None:
        """Register a tool instance."""
        self.tool_instances[tool_instance.name] = tool_instance

    def register_tools(self, tools: List[Any]) -> None:
        """Register multiple tool instances."""
        for tool in tools:
            self.register_tool(tool)

    def execute(self, tool_name: str, **kwargs) -> Any:
        """Execute a tool by name."""
        tool = self.tool_instances.get(tool_name)
        if not tool:
            raise ValueError(f"Unknown tool: {tool_name}")

        return tool.execute(**kwargs)

    def get_tool_schema(self, tool_name: str) -> Optional[Dict[str, Any]]:
        """Get the schema for a tool."""
        tool = self.tool_instances.get(tool_name)
        if tool and hasattr(tool, 'get_schema'):
            return tool.get_schema()
        return None

    def list_tools(self) -> List[str]:
        """List all registered tools."""
        return list(self.tool_instances.keys())