"""
Editor Module - Executes edit instructions generated by Coder.

The Editor receives:
- EditInstruction objects from Coder
- Execute them on the file system

This completes the Coder → Editor workflow from the design document.
"""

from dataclasses import dataclass
from typing import List, Optional, Dict, Any, Callable
from pathlib import Path
import shutil
import time
import os

from .edit import EditInstruction, EditType, EditCollection

# Try relative imports first, then absolute
try:
    from ..tools.result import ToolResult, ToolStatus, create_success_result, create_error_result
except ImportError:
    from tools.result import ToolResult, ToolStatus, create_success_result, create_error_result


@dataclass
class EditorConfig:
    """Configuration for the Editor module."""
    # Root directory for file operations
    root: Optional[str] = None

    # Create backups before modifying files
    create_backups: bool = True

    # Backup directory name
    backup_dir: str = ".backups"

    # Dry run mode (don't actually modify files)
    dry_run: bool = False

    # Stop on first error
    stop_on_error: bool = True

    # Verify file hash after write
    verify_write: bool = True


class EditorResult:
    """Result of executing edit instructions."""

    def __init__(self):
        self.success: bool = True
        self.edits_executed: int = 0
        self.edits_failed: int = 0
        self.results: List[ToolResult] = []
        self.execution_time: float = 0.0
        self.errors: List[str] = []

    def add_result(self, result: ToolResult):
        """Add an execution result."""
        self.results.append(result)
        if result.success:
            self.edits_executed += 1
        else:
            self.edits_failed += 1
            self.success = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "edits_executed": self.edits_executed,
            "edits_failed": self.edits_failed,
            "execution_time": self.execution_time,
            "errors": self.errors,
        }


class Editor:
    """
    Executes edit instructions on the file system.

    The Editor receives EditInstructions from Coder and executes them.

    Supported edit types:
    - replace: Replace old_text with new_text in a file
    - whole_file: Write entire new_content to a file
    - line_edit: Replace lines in a file (future)
    """

    name = "editor"
    description = "Executes edit instructions on files"

    def __init__(self, config: Optional[EditorConfig] = None):
        """
        Initialize the Editor.

        Args:
            config: Editor configuration
        """
        self.config = config or EditorConfig()

    def execute_edit(self, edit: EditInstruction) -> ToolResult:
        """
        Execute a single edit instruction.

        Args:
            edit: The EditInstruction to execute

        Returns:
            ToolResult with execution outcome
        """
        start = time.time()

        # Validate edit
        valid, error = edit.validate()
        if not valid:
            return create_error_result(
                tool=self.name,
                input_params={"file_path": edit.file_path},
                error=f"Invalid edit: {error}",
                latency=time.time() - start,
                status=ToolStatus.INVALID_INPUT,
            )

        # Resolve file path
        file_path = self._resolve_path(edit.file_path)

        if edit.edit_type == EditType.REPLACE:
            return self._execute_replace(edit, file_path, start)
        elif edit.edit_type == EditType.WHOLE_FILE:
            return self._execute_whole_file(edit, file_path, start)
        elif edit.edit_type == EditType.LINE_EDIT:
            return self._execute_line_edit(edit, file_path, start)
        else:
            return create_error_result(
                tool=self.name,
                input_params={"file_path": edit.file_path},
                error=f"Unsupported edit type: {edit.edit_type}",
                latency=time.time() - start,
                status=ToolStatus.INVALID_INPUT,
            )

    def _resolve_path(self, file_path: str) -> Path:
        """Resolve a file path relative to the editor root."""
        if self.config.root:
            return Path(self.config.root) / file_path
        return Path(file_path)

    def _execute_replace(
        self,
        edit: EditInstruction,
        file_path: Path,
        start: float,
    ) -> ToolResult:
        """Execute a replace edit."""
        try:
            # Check file exists
            if not file_path.exists():
                return create_error_result(
                    tool=self.name,
                    input_params={"file_path": edit.file_path},
                    error=f"File not found: {file_path}",
                    latency=time.time() - start,
                )

            # Read current content
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Check if old_text exists
            if edit.old_text not in content:
                # Try to find approximate match
                closest_match = self._find_closest_match(content, edit.old_text)
                return create_error_result(
                    tool=self.name,
                    input_params={"file_path": edit.file_path, "old_text": edit.old_text},
                    error=f"old_text not found in file. Closest match:\n{closest_match}",
                    latency=time.time() - start,
                )

            # Create backup
            backup_path = None
            if self.config.create_backups:
                backup_path = self._create_backup(file_path)

            if self.config.dry_run:
                new_content = content.replace(edit.old_text, edit.new_text)
                return create_success_result(
                    tool=self.name,
                    input_params={"file_path": edit.file_path, "edit_type": "replace"},
                    output=f"[DRY RUN] Would replace {len(edit.old_text)} chars with {len(edit.new_text)} chars",
                    latency=time.time() - start,
                    metadata={
                        "backup_created": backup_path is not None,
                        "backup_path": str(backup_path) if backup_path else None,
                    }
                )

            # Perform the replacement
            new_content = content.replace(edit.old_text, edit.new_text)

            # Write back
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)

            return create_success_result(
                tool=self.name,
                input_params={"file_path": edit.file_path, "edit_type": "replace"},
                output=f"Replaced {len(edit.old_text)} chars with {len(edit.new_text)} chars",
                latency=time.time() - start,
                metadata={
                    "backup_created": backup_path is not None,
                    "backup_path": str(backup_path) if backup_path else None,
                    "bytes_written": len(new_content.encode('utf-8')),
                }
            )

        except Exception as e:
            return create_error_result(
                tool=self.name,
                input_params={"file_path": edit.file_path},
                error=f"Error executing replace: {str(e)}",
                latency=time.time() - start,
            )

    def _execute_whole_file(
        self,
        edit: EditInstruction,
        file_path: Path,
        start: float,
    ) -> ToolResult:
        """Execute a whole_file edit."""
        try:
            # Create backup if file exists
            backup_path = None
            if file_path.exists() and self.config.create_backups:
                backup_path = self._create_backup(file_path)

            if self.config.dry_run:
                return create_success_result(
                    tool=self.name,
                    input_params={"file_path": edit.file_path, "edit_type": "whole_file"},
                    output=f"[DRY RUN] Would write {len(edit.new_content)} bytes",
                    latency=time.time() - start,
                    metadata={"backup_created": backup_path is not None}
                )

            # Ensure parent directory exists
            file_path.parent.mkdir(parents=True, exist_ok=True)

            # Write new content
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(edit.new_content)

            return create_success_result(
                tool=self.name,
                input_params={"file_path": edit.file_path, "edit_type": "whole_file"},
                output=f"Wrote {len(edit.new_content)} bytes to {edit.file_path}",
                latency=time.time() - start,
                metadata={
                    "backup_created": backup_path is not None,
                    "backup_path": str(backup_path) if backup_path else None,
                    "bytes_written": len(edit.new_content.encode('utf-8')),
                }
            )

        except Exception as e:
            return create_error_result(
                tool=self.name,
                input_params={"file_path": edit.file_path},
                error=f"Error executing whole_file: {str(e)}",
                latency=time.time() - start,
            )

    def _execute_line_edit(
        self,
        edit: EditInstruction,
        file_path: Path,
        start: float,
    ) -> ToolResult:
        """Execute a line_edit edit (future)."""
        return create_error_result(
            tool=self.name,
            input_params={"file_path": edit.file_path, "edit_type": "line_edit"},
            error="line_edit is not yet implemented",
            latency=time.time() - start,
            status=ToolStatus.INVALID_INPUT,
        )

    def _create_backup(self, file_path: Path) -> Optional[Path]:
        """Create a backup of the file."""
        try:
            backup_dir = file_path.parent / self.config.backup_dir
            backup_dir.mkdir(parents=True, exist_ok=True)

            timestamp = time.strftime("%Y%m%d_%H%M%S")
            backup_path = backup_dir / f"{file_path.name}.{timestamp}.bak"

            shutil.copy2(file_path, backup_path)
            return backup_path
        except Exception:
            return None

    def _find_closest_match(self, content: str, target: str, max_context: int = 200) -> str:
        """Find the closest matching text in content."""
        # Try to find partial matches
        lines = content.split('\n')
        target_lines = target.split('\n')

        if len(target_lines) > 1:
            # Multi-line target - try to find first line
            first_line = target_lines[0].strip()
            for i, line in enumerate(lines):
                if first_line in line:
                    start = max(0, i - 1)
                    end = min(len(lines), i + len(target_lines) + 2)
                    return '\n'.join(f"{j+1}: {lines[j]}" for j in range(start, end))

        # Single line - show nearby context
        idx = content.find(target[:50]) if len(target) > 50 else content.find(target)
        if idx >= 0:
            start = max(0, idx - 50)
            end = min(len(content), idx + len(target) + 50)
            return f"...{content[start:end]}..."

        return target[:100]  # Fallback

    def execute_collection(
        self,
        collection: EditCollection,
        on_result: Optional[Callable[[ToolResult], None]] = None,
    ) -> EditorResult:
        """
        Execute all edits in an EditCollection.

        Args:
            collection: EditCollection with all edits to execute
            on_result: Optional callback for each result

        Returns:
            EditorResult with summary of all executions
        """
        start_time = time.time()
        result = EditorResult()

        for edit in collection.edits:
            exec_result = self.execute_edit(edit)
            result.add_result(exec_result)

            if on_result:
                on_result(exec_result)

            if not exec_result.success and self.config.stop_on_error:
                break

        result.execution_time = time.time() - start_time
        return result


# Global editor instance for convenience
_default_editor: Optional[Editor] = None


def get_editor(config: Optional[EditorConfig] = None) -> Editor:
    """Get the default editor instance."""
    global _default_editor
    if _default_editor is None or config is not None:
        _default_editor = Editor(config)
    return _default_editor