"""
Coder Pipeline - Integrates Coder with Planner for the full fix workflow.

Following design in design_documents/Coder.md:
- Receives input from Planner (fix_plan + context)
- Outputs structured edit instructions for Editor
- Supports retry loop when tests fail
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, TYPE_CHECKING
from pathlib import Path
import time

from .coder import Coder, CoderConfig
from .edit import EditInstruction, EditType, EditCollection

# Try relative imports first, then absolute
try:
    from ..llm import ChatMessage
except ImportError:
    from llm import ChatMessage

if TYPE_CHECKING:
    from ..llm import BaseLLM
    from ..planner.state import PlanState


@dataclass
class CoderInput:
    """
    Input to the Coder Pipeline.

    This is typically generated by the Planner pipeline.
    """
    issue: str
    fix_plan: Dict[str, Any]  # Planner's output
    target_file_contents: Dict[str, str]  # file_path -> content
    retrieved_context: List[Dict[str, Any]] = field(default_factory=list)
    previous_diff: Optional[str] = None
    test_error: Optional[str] = None
    retry_count: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CoderOutput:
    """
    Output from the Coder Pipeline.

    Contains the edit instructions ready for the Editor.
    """
    success: bool
    edit_collection: EditCollection
    execution_time: float = 0.0
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "edit_collection": self.edit_collection.to_dict(),
            "execution_time": self.execution_time,
            "errors": self.errors,
            "warnings": self.warnings,
            "metadata": self.metadata,
        }


class CoderPipeline:
    """
    Pipeline that orchestrates Coder with retry logic.

    Usage:
        pipeline = CoderPipeline(llm=llm)
        output = pipeline.run(input_data)

        for edit in output.edit_collection.edits:
            editor.execute(edit)
    """

    def __init__(
        self,
        config: Optional[CoderConfig] = None,
        llm: Optional["BaseLLM"] = None,
    ):
        """
        Initialize the Coder Pipeline.

        Args:
            config: Optional Coder configuration
            llm: Optional LLM for complex edit generation
        """
        self.coder = Coder(config=config, llm=llm)

    def run(self, input_data: CoderInput) -> CoderOutput:
        """
        Run the Coder pipeline on the given input.

        Args:
            input_data: CoderInput containing fix plan and file contents

        Returns:
            CoderOutput with generated edit instructions
        """
        start_time = time.time()
        errors = []
        warnings = []

        # Validate input
        if not input_data.target_file_contents:
            warnings.append("No target file contents provided")

        if not input_data.fix_plan.get("target_files"):
            warnings.append("No target files specified in fix plan")

        # Generate edits
        collection = self.coder.generate_edits(
            issue=input_data.issue,
            fix_plan=input_data.fix_plan,
            target_file_contents=input_data.target_file_contents,
            context=input_data.retrieved_context,
            previous_diff=input_data.previous_diff,
            test_error=input_data.test_error,
            retry_count=input_data.retry_count,
        )

        # Validate generated edits
        is_valid, validation_errors = collection.is_valid()
        if not is_valid:
            errors.extend(validation_errors)

        # Check for warnings
        if not collection.edits:
            warnings.append("No edits were generated")

        if collection.edits:
            # Check if edits target only allowed files
            planner_files = set(input_data.fix_plan.get("target_files", []))
            edit_files = set(collection.get_target_files())

            if not planner_files.issuperset(edit_files):
                extra_files = edit_files - planner_files
                if not self.coder.config.allow_extra_files:
                    warnings.append(f"Edits target files not in planner's list: {extra_files}")

        execution_time = time.time() - start_time

        return CoderOutput(
            success=is_valid and len(collection.edits) > 0,
            edit_collection=collection,
            execution_time=execution_time,
            errors=errors,
            warnings=warnings,
            metadata={
                "input_target_files": input_data.fix_plan.get("target_files", []),
                "output_target_files": collection.get_target_files(),
                "edit_count": len(collection.edits),
            }
        )

    def run_with_retry(
        self,
        input_data: CoderInput,
        max_retries: int = 3,
    ) -> CoderOutput:
        """
        Run the Coder pipeline with automatic retry on validation failure.

        Args:
            input_data: CoderInput containing fix plan and file contents
            max_retries: Maximum number of retry attempts

        Returns:
            CoderOutput with generated edit instructions
        """
        output = self.run(input_data)

        for attempt in range(1, max_retries + 1):
            if output.success:
                break

            # Prepare retry input
            input_data.retry_count = attempt
            input_data.previous_diff = self._generate_diff_summary(output)
            input_data.test_error = input_data.metadata.get("last_test_error")

            # Re-run
            output = self.run(input_data)

        return output

    def _generate_diff_summary(self, output: CoderOutput) -> str:
        """Generate a summary of the previous diff for retry context."""
        lines = ["Previous edits that failed:"]
        for i, edit in enumerate(output.edit_collection.edits, 1):
            lines.append(f"\n{i}. {edit.file_path} ({edit.edit_type.value})")
            lines.append(f"   Reason: {edit.reason}")
            if edit.old_text:
                lines.append(f"   Old: {edit.old_text[:100]}...")
                lines.append(f"   New: {edit.new_text[:100]}...")

        return "\n".join(lines)


def create_coder_pipeline_from_planner(
    plan_state: "PlanState",
    file_contents: Dict[str, str],
    context: Optional[List[Dict[str, Any]]] = None,
    llm: Optional["BaseLLM"] = None,
) -> CoderPipeline:
    """
    Create a CoderPipeline from a Planner's PlanState.

    This is the main integration point between Planner and Coder.

    Args:
        plan_state: Planner's PlanState output
        file_contents: Target file contents
        context: Retrieved context from RAG
        llm: Optional LLM instance

    Returns:
        Configured CoderPipeline ready to run
    """
    # Convert PlanState to fix_plan format
    fix_plan = {
        "bug_reason": plan_state.thinking[:500] if plan_state.thinking else "See plan",
        "target_files": list(set(step.target for step in plan_state.plan)),
        "fix_strategy": "; ".join(s.description for s in plan_state.plan[:3]),
        "target_symbols": [],
        "risk_level": "medium",
    }

    # Build input
    input_data = CoderInput(
        issue=plan_state.task,
        fix_plan=fix_plan,
        target_file_contents=file_contents,
        retrieved_context=context or plan_state.context,
    )

    # Create pipeline
    pipeline = CoderPipeline(llm=llm)

    return pipeline, input_data